// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtjEaroWS_RjoMjJu8X04rUx61-AYK094',
    appId: '1:364061060821:web:181fb9784e14c8a1337c5c',
    messagingSenderId: '364061060821',
    projectId: 'email-attachment-b3504',
    authDomain: 'email-attachment-b3504.firebaseapp.com',
    storageBucket: 'email-attachment-b3504.appspot.com',
    measurementId: 'G-CCVLYGQWWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPLaMtKERhBdzXfB9KOIoi0ZI6rztfZ74',
    appId: '1:364061060821:android:1cede8b89811aa4a337c5c',
    messagingSenderId: '364061060821',
    projectId: 'email-attachment-b3504',
    storageBucket: 'email-attachment-b3504.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsdh0sUmQXB7vwPw7kyWsdf7bJ2sdzhNE',
    appId: '1:364061060821:ios:d9b6dafeaf2f4560337c5c',
    messagingSenderId: '364061060821',
    projectId: 'email-attachment-b3504',
    storageBucket: 'email-attachment-b3504.appspot.com',
    iosBundleId: 'com.example.emailattachment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsdh0sUmQXB7vwPw7kyWsdf7bJ2sdzhNE',
    appId: '1:364061060821:ios:d9b6dafeaf2f4560337c5c',
    messagingSenderId: '364061060821',
    projectId: 'email-attachment-b3504',
    storageBucket: 'email-attachment-b3504.appspot.com',
    iosBundleId: 'com.example.emailattachment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtjEaroWS_RjoMjJu8X04rUx61-AYK094',
    appId: '1:364061060821:web:db823a1fbb564ea0337c5c',
    messagingSenderId: '364061060821',
    projectId: 'email-attachment-b3504',
    authDomain: 'email-attachment-b3504.firebaseapp.com',
    storageBucket: 'email-attachment-b3504.appspot.com',
    measurementId: 'G-DV01JD1P2L',
  );
}
